-- Truck Command Database Schema Migration
-- Generated: 2026-01-24
-- This file creates all tables for the Truck Command application

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "postgis" SCHEMA extensions;

-- ============================================
-- CORE USER & COMPANY TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL,
    full_name TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    company_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    fleet_size TEXT,
    subscription_tier TEXT DEFAULT 'free'::text,
    stripe_customer_id TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    dismissed_tutorials TEXT[] DEFAULT '{}'::text[],
    has_demo_data BOOLEAN DEFAULT false,
    demo_data_created_at TIMESTAMP WITH TIME ZONE,
    operator_type TEXT,
    primary_focus TEXT,
    onboarding_completed BOOLEAN DEFAULT false,
    onboarding_completed_at TIMESTAMP WITH TIME ZONE,
    setup_checklist_dismissed BOOLEAN DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS company_info (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    legal_name TEXT,
    dba_name TEXT,
    logo_url TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    mc_number TEXT,
    dot_number TEXT,
    ein TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT company_info_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS company_profiles (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    country TEXT,
    mc_number TEXT,
    dot_number TEXT,
    ein TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT company_profiles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_preferences (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    theme VARCHAR(10) DEFAULT 'system'::character varying,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT user_preferences_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS user_settings (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    setting_key TEXT NOT NULL,
    setting_value JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT user_settings_pkey PRIMARY KEY (id),
    CONSTRAINT user_settings_user_id_setting_key_key UNIQUE (user_id, setting_key)
);

-- ============================================
-- SUBSCRIPTION & BILLING TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS subscriptions (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'trialing'::character varying,
    plan VARCHAR(50),
    billing_cycle VARCHAR(20),
    amount NUMERIC(10,2),
    stripe_customer_id VARCHAR(255),
    stripe_subscription_id VARCHAR(255),
    card_last_four VARCHAR(4),
    trial_starts_at TIMESTAMP WITH TIME ZONE,
    trial_ends_at TIMESTAMP WITH TIME ZONE,
    current_period_starts_at TIMESTAMP WITH TIME ZONE,
    current_period_ends_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    checkout_session_id TEXT,
    cancel_at_period_end BOOLEAN DEFAULT false,
    canceled_at TIMESTAMP WITH TIME ZONE,
    checkout_initiated_at TIMESTAMP WITH TIME ZONE,
    cancellation_reason TEXT,
    cancellation_feedback TEXT,
    scheduled_amount NUMERIC(10,2),
    paused_at TIMESTAMP WITH TIME ZONE,
    pause_resumes_at TIMESTAMP WITH TIME ZONE,
    payment_failed_at TIMESTAMP WITH TIME ZONE,
    payment_failure_count INTEGER DEFAULT 0,
    next_payment_retry_at TIMESTAMP WITH TIME ZONE,
    trial_ending_notified_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT subscriptions_user_id_unique UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS processed_sessions (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key TEXT NOT NULL,
    user_id UUID NOT NULL,
    session_id TEXT,
    processed_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT processed_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT processed_sessions_idempotency_key_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS launch_waitlist (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    name TEXT,
    source TEXT DEFAULT 'signup_page'::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    notified_at TIMESTAMP WITH TIME ZONE,
    subscribed BOOLEAN DEFAULT true,
    CONSTRAINT launch_waitlist_pkey PRIMARY KEY (id),
    CONSTRAINT launch_waitlist_email_key UNIQUE (email)
);

-- ============================================
-- FLEET MANAGEMENT TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS drivers (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    license TEXT,
    license_expiry DATE,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    status TEXT DEFAULT 'Active'::text,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    medical_card_expiry DATE,
    hire_date DATE,
    image_url TEXT,
    eld_external_id VARCHAR(255),
    eld_provider VARCHAR(50),
    hos_status VARCHAR(20),
    hos_available_drive_minutes INTEGER,
    hos_available_shift_minutes INTEGER,
    hos_available_cycle_minutes INTEGER,
    hos_last_updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT drivers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vehicles (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    name TEXT,
    type TEXT,
    make TEXT,
    model TEXT,
    year INTEGER,
    vin TEXT,
    license_plate TEXT,
    status TEXT DEFAULT 'Active'::text,
    color TEXT,
    mpg NUMERIC(10,2),
    fuel_type TEXT,
    tank_capacity NUMERIC(10,2),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    image_url TEXT,
    registration_expiry DATE,
    insurance_expiry DATE,
    inspection_expiry DATE,
    assigned_driver_id UUID,
    eld_external_id VARCHAR(255),
    eld_provider VARCHAR(50),
    eld_device_serial VARCHAR(100),
    last_known_location JSONB,
    last_location_at TIMESTAMP WITH TIME ZONE,
    eld_last_sync_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT vehicles_pkey PRIMARY KEY (id)
);

-- ============================================
-- CUSTOMER & LOAD MANAGEMENT TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS customers (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    company_name TEXT NOT NULL,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    customer_type TEXT,
    status TEXT DEFAULT 'Active'::text,
    notes TEXT,
    tax_exempt BOOLEAN DEFAULT false,
    tax_id TEXT,
    payment_terms TEXT DEFAULT 'Net 15'::text,
    credit_limit NUMERIC(10,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS loads (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    load_number TEXT NOT NULL,
    customer TEXT NOT NULL,
    customer_id UUID,
    status TEXT DEFAULT 'Pending'::text,
    origin TEXT,
    destination TEXT,
    distance NUMERIC(10,2),
    pickup_date DATE,
    delivery_date DATE,
    rate NUMERIC(10,2) DEFAULT 0,
    driver TEXT,
    driver_id UUID,
    vehicle_id UUID,
    description TEXT,
    notes TEXT,
    completed_at TIMESTAMP WITH TIME ZONE,
    completed_by UUID,
    actual_delivery_date TIMESTAMP WITH TIME ZONE,
    received_by TEXT,
    completion_notes TEXT,
    pod_documents JSONB,
    delivery_rating INTEGER,
    additional_mileage NUMERIC(10,2) DEFAULT 0,
    additional_charges NUMERIC(10,2) DEFAULT 0,
    additional_charges_description TEXT,
    final_rate NUMERIC(10,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    factored BOOLEAN DEFAULT false,
    factoring_company TEXT,
    factored_at TIMESTAMP WITH TIME ZONE,
    factored_amount NUMERIC(10,2),
    truck_info TEXT,
    actual_delivery_time TIME WITHOUT TIME ZONE,
    CONSTRAINT loads_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS load_stops (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    load_id UUID NOT NULL,
    stop_number INTEGER NOT NULL,
    location TEXT NOT NULL,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    scheduled_date TIMESTAMP WITH TIME ZONE,
    actual_date TIMESTAMP WITH TIME ZONE,
    stop_type TEXT,
    notes TEXT,
    status TEXT DEFAULT 'Pending'::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT load_stops_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS load_documents (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    load_id UUID NOT NULL,
    document_type TEXT NOT NULL,
    file_name TEXT,
    file_path TEXT NOT NULL,
    uploaded_by UUID,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT load_documents_pkey PRIMARY KEY (id)
);

-- ============================================
-- FINANCIAL TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS earnings (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    load_id UUID,
    amount NUMERIC(10,2) NOT NULL,
    date DATE NOT NULL,
    source TEXT NOT NULL DEFAULT 'Factoring'::text,
    description TEXT,
    factoring_company TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT earnings_pkey PRIMARY KEY (id),
    CONSTRAINT unique_load_earnings UNIQUE (load_id, source)
);

CREATE TABLE IF NOT EXISTS expense_categories (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID,
    name TEXT NOT NULL,
    description TEXT,
    is_default BOOLEAN DEFAULT false,
    icon TEXT,
    color TEXT,
    tax_deductible BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT expense_categories_pkey PRIMARY KEY (id),
    CONSTRAINT expense_categories_user_id_name_key UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS expenses (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    date DATE NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    payment_method TEXT,
    vehicle_id UUID,
    deductible BOOLEAN DEFAULT true,
    receipt_image TEXT,
    notes TEXT,
    load_id UUID,
    driver_id UUID,
    location TEXT,
    tax_category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS fuel_entries (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    vehicle_id UUID,
    driver_id UUID,
    date DATE NOT NULL,
    gallons NUMERIC(10,3) NOT NULL,
    price_per_gallon NUMERIC(10,3) NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    odometer NUMERIC(10,1),
    state TEXT,
    state_name TEXT,
    location TEXT,
    fuel_type TEXT,
    is_complete_fill BOOLEAN DEFAULT true,
    notes TEXT,
    receipt_image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    expense_id UUID,
    payment_method TEXT DEFAULT 'Credit Card'::text,
    CONSTRAINT fuel_entries_pkey PRIMARY KEY (id)
);

-- ============================================
-- INVOICING TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS invoices (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    invoice_number TEXT NOT NULL,
    customer TEXT NOT NULL,
    customer_id UUID,
    load_id UUID,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    po_number TEXT,
    terms TEXT,
    notes TEXT,
    subtotal NUMERIC(10,2) DEFAULT 0,
    tax_rate NUMERIC(5,2) DEFAULT 0,
    tax_amount NUMERIC(10,2) DEFAULT 0,
    total NUMERIC(10,2) DEFAULT 0,
    amount_paid NUMERIC(10,2) DEFAULT 0,
    payment_date DATE,
    status TEXT DEFAULT 'Draft'::text,
    last_sent TIMESTAMP WITH TIME ZONE,
    customer_email TEXT,
    customer_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    payment_terms TEXT DEFAULT 'Net 15'::text,
    CONSTRAINT invoices_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS invoice_items (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    invoice_id UUID NOT NULL,
    description TEXT NOT NULL,
    quantity NUMERIC(10,2) NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0,
    tax_rate NUMERIC(5,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT invoice_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS invoice_activities (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    invoice_id UUID NOT NULL,
    user_id UUID,
    user_name TEXT,
    activity_type TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT invoice_activities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS payments (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    invoice_id UUID,
    amount NUMERIC(10,2) NOT NULL,
    date DATE NOT NULL,
    method TEXT NOT NULL,
    reference TEXT,
    description TEXT,
    notes TEXT,
    status TEXT DEFAULT 'completed'::text,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

-- ============================================
-- IFTA & MILEAGE TRACKING TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS driver_mileage_trips (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    vehicle_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active'::text,
    start_date DATE NOT NULL,
    end_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT driver_mileage_trips_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS driver_mileage_crossings (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    trip_id UUID NOT NULL,
    state TEXT NOT NULL,
    state_name TEXT,
    odometer INTEGER NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    crossing_date DATE NOT NULL,
    CONSTRAINT driver_mileage_crossings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ifta_trip_records (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID,
    quarter TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    vehicle_id UUID,
    driver_id UUID,
    load_id UUID,
    start_jurisdiction TEXT,
    end_jurisdiction TEXT,
    total_miles NUMERIC(10,2),
    gallons NUMERIC(10,3),
    fuel_cost NUMERIC(10,2),
    starting_odometer NUMERIC(10,2),
    ending_odometer NUMERIC(10,2),
    is_fuel_only BOOLEAN DEFAULT false,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    is_imported BOOLEAN DEFAULT false,
    mileage_trip_id UUID,
    source VARCHAR(50) DEFAULT NULL::character varying,
    eld_connection_id UUID,
    eld_ifta_mileage_id UUID,
    data_source VARCHAR(20) DEFAULT 'manual'::character varying,
    CONSTRAINT ifta_trip_records_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ifta_trip_state_mileage (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    trip_id UUID,
    user_id UUID,
    jurisdiction TEXT NOT NULL,
    miles NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT ifta_trip_state_mileage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ifta_reports (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID,
    quarter TEXT NOT NULL,
    year INTEGER NOT NULL,
    total_miles NUMERIC(10,2),
    total_gallons NUMERIC(10,3),
    total_tax NUMERIC(10,2),
    status TEXT DEFAULT 'draft'::text,
    submitted_at TIMESTAMP WITH TIME ZONE,
    jurisdiction_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT ifta_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ifta_report_details (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    report_id UUID NOT NULL,
    state TEXT NOT NULL,
    miles NUMERIC(10,2) DEFAULT 0,
    gallons NUMERIC(10,3) DEFAULT 0,
    tax_rate NUMERIC(10,4) DEFAULT 0,
    tax_due NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT ifta_report_details_pkey PRIMARY KEY (id),
    CONSTRAINT ifta_report_details_report_id_state_key UNIQUE (report_id, state)
);

CREATE TABLE IF NOT EXISTS ifta_tax_rates (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    jurisdiction TEXT NOT NULL,
    base_rate NUMERIC(10,3) NOT NULL,
    surcharge NUMERIC(10,3) DEFAULT 0,
    total_rate NUMERIC(10,3),
    effective_date DATE NOT NULL,
    expiration_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT ifta_tax_rates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ifta_automated_mileage (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    vehicle_id UUID,
    eld_vehicle_id TEXT,
    eld_provider TEXT,
    jurisdiction TEXT NOT NULL,
    quarter TEXT NOT NULL,
    year INTEGER NOT NULL,
    total_miles NUMERIC(12,2) NOT NULL DEFAULT 0,
    last_odometer NUMERIC(12,2),
    last_latitude NUMERIC(10,7),
    last_longitude NUMERIC(10,7),
    last_updated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ifta_automated_mileage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ifta_automated_crossings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    vehicle_id UUID,
    eld_vehicle_id TEXT,
    eld_provider TEXT,
    from_jurisdiction TEXT NOT NULL,
    to_jurisdiction TEXT NOT NULL,
    crossing_time TIMESTAMP WITH TIME ZONE NOT NULL,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    odometer_at_crossing NUMERIC(12,2),
    quarter TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ifta_automated_crossings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ifta_realtime_mileage (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    vehicle_id UUID,
    eld_vehicle_id TEXT,
    jurisdiction TEXT NOT NULL,
    quarter TEXT NOT NULL,
    miles NUMERIC(12,2) NOT NULL DEFAULT 0,
    source TEXT DEFAULT 'webhook'::text,
    last_breadcrumb_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT ifta_realtime_mileage_pkey PRIMARY KEY (id)
);

-- ============================================
-- ELD INTEGRATION TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS eld_connections (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    provider TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'::text,
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TIMESTAMP WITH TIME ZONE,
    company_id TEXT,
    company_name TEXT,
    scopes TEXT[],
    last_sync_at TIMESTAMP WITH TIME ZONE,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    eld_provider_name TEXT,
    sync_frequency_minutes INTEGER DEFAULT 60,
    metadata JSONB DEFAULT '{}'::jsonb,
    connection_token TEXT,
    external_connection_id VARCHAR(255),
    permissions JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT eld_connections_pkey PRIMARY KEY (id),
    CONSTRAINT eld_connections_user_id_provider_key UNIQUE (user_id, provider)
);

CREATE TABLE IF NOT EXISTS eld_driver_mappings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    eld_driver_id TEXT NOT NULL,
    eld_driver_name TEXT,
    eld_driver_email TEXT,
    local_driver_id UUID,
    is_active BOOLEAN DEFAULT true,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_driver_mappings_pkey PRIMARY KEY (id),
    CONSTRAINT eld_driver_mappings_connection_id_eld_driver_id_key UNIQUE (connection_id, eld_driver_id)
);

CREATE TABLE IF NOT EXISTS eld_vehicle_mappings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    eld_vehicle_id TEXT NOT NULL,
    eld_vehicle_name TEXT,
    eld_vehicle_vin TEXT,
    local_vehicle_id UUID,
    is_active BOOLEAN DEFAULT true,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_vehicle_mappings_pkey PRIMARY KEY (id),
    CONSTRAINT eld_vehicle_mappings_connection_id_eld_vehicle_id_key UNIQUE (connection_id, eld_vehicle_id)
);

CREATE TABLE IF NOT EXISTS eld_entity_mappings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    connection_id UUID,
    entity_type VARCHAR(20) NOT NULL,
    local_id UUID NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    external_name VARCHAR(255),
    auto_matched BOOLEAN DEFAULT false,
    match_confidence NUMERIC(3,2),
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_entity_mappings_pkey PRIMARY KEY (id),
    CONSTRAINT eld_entity_mappings_connection_id_entity_type_external_id_key UNIQUE (connection_id, entity_type, external_id)
);

CREATE TABLE IF NOT EXISTS eld_hos_logs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    driver_mapping_id UUID,
    eld_driver_id TEXT NOT NULL,
    log_date DATE NOT NULL,
    duty_status TEXT,
    driving_hours NUMERIC(5,2),
    on_duty_hours NUMERIC(5,2),
    off_duty_hours NUMERIC(5,2),
    sleeper_hours NUMERIC(5,2),
    cycle_hours_remaining NUMERIC(5,2),
    violations JSONB,
    raw_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_hos_logs_pkey PRIMARY KEY (id),
    CONSTRAINT eld_hos_logs_connection_id_eld_driver_id_log_date_key UNIQUE (connection_id, eld_driver_id, log_date)
);

CREATE TABLE IF NOT EXISTS eld_hos_daily_logs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    connection_id UUID,
    driver_id UUID,
    external_driver_id VARCHAR(255),
    log_date DATE NOT NULL,
    driving_minutes INTEGER DEFAULT 0,
    on_duty_minutes INTEGER DEFAULT 0,
    sleeper_minutes INTEGER DEFAULT 0,
    off_duty_minutes INTEGER DEFAULT 0,
    available_drive_minutes INTEGER,
    available_shift_minutes INTEGER,
    available_cycle_minutes INTEGER,
    violations JSONB DEFAULT '[]'::jsonb,
    certified BOOLEAN DEFAULT false,
    certified_at TIMESTAMP WITH TIME ZONE,
    cycle_type VARCHAR(20) DEFAULT '70_8'::character varying,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_hos_daily_logs_pkey PRIMARY KEY (id),
    CONSTRAINT eld_hos_daily_logs_driver_id_log_date_key UNIQUE (driver_id, log_date)
);

CREATE TABLE IF NOT EXISTS eld_vehicle_locations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    vehicle_mapping_id UUID,
    eld_vehicle_id TEXT NOT NULL,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    speed_mph NUMERIC(5,1),
    heading INTEGER,
    odometer NUMERIC(10,1),
    engine_hours NUMERIC(10,1),
    location_time TIMESTAMP WITH TIME ZONE NOT NULL,
    address TEXT,
    city TEXT,
    state TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_vehicle_locations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eld_ifta_mileage (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    vehicle_mapping_id UUID,
    eld_vehicle_id TEXT NOT NULL,
    jurisdiction TEXT NOT NULL,
    miles NUMERIC(10,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    quarter TEXT,
    year INTEGER,
    eld_trip_id TEXT,
    imported_to_ifta BOOLEAN DEFAULT false,
    ifta_trip_id UUID,
    raw_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_ifta_mileage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eld_fault_codes (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    vehicle_mapping_id UUID,
    eld_vehicle_id TEXT NOT NULL,
    code TEXT NOT NULL,
    description TEXT,
    severity TEXT,
    first_observed_at TIMESTAMP WITH TIME ZONE,
    last_observed_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    resolved_at TIMESTAMP WITH TIME ZONE,
    raw_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_fault_codes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eld_sync_history (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    sync_type TEXT NOT NULL,
    status TEXT NOT NULL,
    records_synced INTEGER DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    completed_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB,
    CONSTRAINT eld_sync_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eld_sync_jobs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    sync_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'pending'::character varying,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    records_synced INTEGER DEFAULT 0,
    error_message TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT eld_sync_jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eld_webhook_events (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    provider TEXT NOT NULL,
    event_type TEXT NOT NULL,
    organization_id UUID,
    payload JSONB,
    status TEXT NOT NULL DEFAULT 'pending'::text,
    error_message TEXT,
    result JSONB,
    processing_time_ms INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    processed_at TIMESTAMP WITH TIME ZONE,
    user_id UUID,
    connection_id UUID,
    CONSTRAINT eld_webhook_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eld_gps_breadcrumbs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    vehicle_id UUID,
    eld_vehicle_id TEXT,
    eld_provider TEXT,
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    jurisdiction TEXT,
    odometer NUMERIC(12,2),
    speed_mph NUMERIC(6,2),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT eld_gps_breadcrumbs_pkey PRIMARY KEY (id)
);

-- ============================================
-- GPS & LOCATION TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS gps_breadcrumbs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    eld_vehicle_id TEXT NOT NULL,
    eld_provider TEXT NOT NULL,
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    jurisdiction TEXT,
    speed_mph NUMERIC(6,2),
    heading INTEGER,
    odometer_miles NUMERIC(12,2),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT gps_breadcrumbs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vehicle_current_locations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    vehicle_id UUID,
    eld_vehicle_id TEXT NOT NULL,
    eld_provider TEXT NOT NULL,
    latitude NUMERIC(10,7) NOT NULL,
    longitude NUMERIC(10,7) NOT NULL,
    jurisdiction TEXT,
    speed_mph NUMERIC(6,2),
    heading INTEGER,
    odometer_miles NUMERIC(12,2),
    engine_hours NUMERIC(10,2),
    address TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT vehicle_current_locations_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_current_locations_organization_id_eld_vehicle_id_key UNIQUE (organization_id, eld_vehicle_id)
);

CREATE TABLE IF NOT EXISTS vehicle_active_faults (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    vehicle_id UUID,
    eld_vehicle_id TEXT NOT NULL,
    eld_provider TEXT NOT NULL,
    code TEXT NOT NULL,
    description TEXT,
    severity TEXT DEFAULT 'warning'::text,
    source TEXT,
    is_active BOOLEAN DEFAULT true,
    first_observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT vehicle_active_faults_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_active_faults_organization_id_eld_vehicle_id_code_key UNIQUE (organization_id, eld_vehicle_id, code)
);

CREATE TABLE IF NOT EXISTS driver_hos_status (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    driver_id UUID,
    eld_driver_id TEXT NOT NULL,
    eld_provider TEXT NOT NULL,
    duty_status TEXT NOT NULL,
    status_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    vehicle_id TEXT,
    location_description TEXT,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    drive_time_remaining_ms BIGINT,
    shift_time_remaining_ms BIGINT,
    cycle_time_remaining_ms BIGINT,
    break_time_remaining_ms BIGINT,
    has_violation BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT driver_hos_status_pkey PRIMARY KEY (id),
    CONSTRAINT driver_hos_status_organization_id_eld_driver_id_key UNIQUE (organization_id, eld_driver_id)
);

-- ============================================
-- COMPLIANCE & MAINTENANCE TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS compliance_items (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    title TEXT NOT NULL,
    compliance_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_name TEXT NOT NULL,
    document_number TEXT,
    issue_date DATE,
    expiration_date DATE NOT NULL,
    issuing_authority TEXT,
    notes TEXT,
    status TEXT NOT NULL,
    document_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT compliance_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS maintenance_records (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    truck_id UUID NOT NULL,
    description TEXT,
    due_date DATE,
    completed_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    vehicle_id UUID,
    odometer_at_service NUMERIC(10,2),
    cost NUMERIC(10,2),
    expense_id UUID,
    CONSTRAINT maintenance_records_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reminders (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    due_date DATE NOT NULL,
    completed BOOLEAN DEFAULT false,
    completed_at TIMESTAMP WITH TIME ZONE,
    priority TEXT DEFAULT 'Medium'::text,
    reminder_type TEXT,
    entity_type TEXT,
    entity_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT reminders_pkey PRIMARY KEY (id)
);

-- ============================================
-- NOTIFICATION TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS notifications (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    read_at TIMESTAMP WITH TIME ZONE,
    notification_type TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    link_to TEXT,
    due_date TIMESTAMP WITH TIME ZONE,
    urgency TEXT DEFAULT 'NORMAL'::text,
    email_sent BOOLEAN DEFAULT false,
    sms_sent BOOLEAN DEFAULT false,
    delivered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id UUID NOT NULL DEFAULT extensions.uuid_generate_v4(),
    user_id UUID NOT NULL,
    preferences JSONB NOT NULL DEFAULT '{"app": {"expenses": true, "invoices": true, "documents": true, "reminders": true}, "sms": {"expenses": false, "invoices": false, "documents": false, "reminders": true}, "email": {"expenses": true, "invoices": true, "documents": true, "reminders": true}}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT notification_preferences_pkey PRIMARY KEY (id)
);

-- ============================================
-- POSTGIS SYSTEM TABLES (Views - recreated by PostGIS extension)
-- ============================================

-- Note: geography_columns, geometry_columns, and spatial_ref_sys
-- are created automatically by the PostGIS extension.
-- Do not manually create these tables.

-- ============================================
-- VIEW: IFTA Trips with Mileage
-- ============================================

CREATE OR REPLACE VIEW ifta_trips_with_mileage AS
SELECT
    itr.id,
    itr.user_id,
    itr.quarter,
    itr.start_date,
    itr.end_date,
    itr.vehicle_id,
    itr.driver_id,
    itr.load_id,
    itr.start_jurisdiction,
    itr.end_jurisdiction,
    itr.total_miles,
    itr.gallons,
    itr.fuel_cost,
    itr.starting_odometer,
    itr.ending_odometer,
    itr.is_fuel_only,
    itr.notes,
    itr.created_at,
    itr.updated_at,
    itr.is_imported,
    itr.mileage_trip_id,
    itr.source,
    dmt.start_date AS mileage_start_date,
    dmt.end_date AS mileage_end_date,
    dmt.vehicle_id AS mileage_vehicle_id,
    (SELECT COUNT(*) FROM driver_mileage_crossings dmc WHERE dmc.trip_id = dmt.id) AS crossing_count
FROM ifta_trip_records itr
LEFT JOIN driver_mileage_trips dmt ON itr.mileage_trip_id = dmt.id;
