-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Anyone can insert processed sessions" ON "public"."processed_sessions";
DROP POLICY IF EXISTS "Users can view their own processed sessions" ON "public"."processed_sessions";

-- Create processed_sessions table if it doesn't exist
CREATE TABLE IF NOT EXISTS "public"."processed_sessions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "idempotency_key" text NOT NULL,
    "user_id" uuid NOT NULL,
    "session_id" text,
    "processed_at" timestamp with time zone DEFAULT now(),
    "created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "processed_sessions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "processed_sessions_idempotency_key_key" UNIQUE ("idempotency_key"),
    CONSTRAINT "processed_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES auth.users(id)
);

-- Add RLS policies for processed_sessions
ALTER TABLE "public"."processed_sessions" ENABLE ROW LEVEL SECURITY;

-- Recreate the policies
CREATE POLICY "Anyone can insert processed sessions" ON "public"."processed_sessions"
FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Users can view their own processed sessions" ON "public"."processed_sessions"
FOR SELECT TO public USING ((auth.uid() = user_id));

-- Add new columns to subscriptions table if they don't exist
ALTER TABLE "public"."subscriptions" 
ADD COLUMN IF NOT EXISTS "plan" character varying(50),
ADD COLUMN IF NOT EXISTS "billing_cycle" character varying(20),
ADD COLUMN IF NOT EXISTS "amount" numeric(10,2),
ADD COLUMN IF NOT EXISTS "stripe_customer_id" character varying(255),
ADD COLUMN IF NOT EXISTS "stripe_subscription_id" character varying(255),
ADD COLUMN IF NOT EXISTS "card_last_four" character varying(4),
ADD COLUMN IF NOT EXISTS "current_period_starts_at" timestamp with time zone,
ADD COLUMN IF NOT EXISTS "current_period_ends_at" timestamp with time zone,
ADD COLUMN IF NOT EXISTS "cancel_at_period_end" boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS "canceled_at" timestamp with time zone DEFAULT null,
ADD COLUMN IF NOT EXISTS "checkout_session_id" character varying(255) DEFAULT null,
ADD COLUMN IF NOT EXISTS "checkout_initiated_at" timestamp with time zone DEFAULT null;
